### ISSUE TITLE
You did not pass the checksum security check, messageKey: checksumError

### ISSUE THREAD

**Issue by iamsujitpranav** [mconf/mconf-web#164]
hi,

I don't want to trouble you in asking this query as you already have made easy the integration of BBB with rails, but I cant help myself in making this thing work out. following is my query.

I had followed steps mentioned in below link.

--> https://github.com/mconf/mconf-web/wiki/Development

 I get this error called "You did not pass the checksum security check," when i am trying to join a room

I had configured my salt&server in setup_conf.yml file,under default block -> webconf_server

Should I have  to add my secret salt anywhere else  ? I had attached screen shot for reference. 

![bbb](https://cloud.githubusercontent.com/assets/7262923/11032527/45f53286-8702-11e5-8348-3e03c50283b4.png)

Please help out on this, let me know where I am doing wrong,

Thanks & regards,
Sujit.

**Comment by daronco** [comment]
Hi,

Take a look at https://github.com/mconf/mconf-web/wiki/Configuration-Files
The file `setup_conf.yml` is used only the first time you setup your database. Afterwards, the configurations are all taken directly from the database, so changing the file won't actually change anything in the application. To change the server URL and salt, do it using the management page: https://github.com/mconf/mconf-web/wiki/Configuring-the-Website

Please use our mailing list at mconf-dev@googlegroups.com for future questions since they might not necessarily be issues/bugs, thanks.
