### ISSUE TITLE
Separate the username from his web conference room's name

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#363]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 453, http://dev.mconf.org/redmine/issues/453
Original Date: 2012-10-10

---

Currently when a user registers he can pick a username that can not be changed later on.

This username is also used to defined the url of his web conference room.
Since we want to enable the user to edit this url, we should create a new field to be used to define his room's identifier, that the user can change whenever he wants to.

Maybe we can use @User.bigbluebutton_room.param@ instead of creating a new field (see https://github.com/mconf/bigbluebutton_rails/blob/master/app/models/bigbluebutton_room.rb#L14).

**Comment by daronco** [comment]
For now users can edit the *name* of their room whenever they want, but not the URL. The URL is still tied to the user's username or to the space's permalink. However, admins do have the option to change the URL of a room.

So the feature is there, but it's controlled, since only admins can access it.
