### ISSUE TITLE
"rbenv install 2.2.0" problem 

### ISSUE THREAD

**Issue by pdifeo** [mconf/mconf-web#885]
Hi,

maybe this is an offtopic issue, but this step is necessary. I have this error and compilation stop

`ossl_ssl.c:119:69: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
`
Someone can help me ?

Regards
Pasquale

**Comment by daronco** [comment]
This might be an issue with ruby 2.2.0, see #184.

We just updated ruby to 2.2.5, which might solve the problem (e30e882e4c02a58b137fbe2887d3c78d6b4ffbb4).
This is not in the wiki yet, it will be updated when a new version of Mconf-Web is out. But you can try to install ruby 2.2.5 instead of 2.2.0 and see if it solves the issue.

**Comment by daronco** [comment]
Mconf-Web 2.3.0 was released and it uses ruby 2.2.5. Wiki pages updated as well.
