### ISSUE TITLE
Add the last sign in to the management list of users

### ISSUE THREAD

**Issue by daronco** [mconf/mconf-web#889]
Add the date of the last sign in of a user to the page `/manage/users` and the filters:
- Last sign in before...
- Last sign in after...

Both filters are dates and should work either alone of together.

Ideally this should be done after #767.

**Comment by RafaFP** [comment]
We should name these fields something like "Most recent sign in before...", because of the way devise names the corresponding fields on the schema. "Last" represents the second most recent sign in date and "Current" represents the most recent sign in date.

To avoid confusion while updating this feature later on, we should adjust the naming or document it clearly on the code.
