### ISSUE TITLE
English strings aren't displayed on labels without translation in other languages

### ISSUE THREAD

**Issue by hipoloco** [mconf/mconf-web#896]
In the latest release (2.3.0), if I set the language in Spanish (for example) all labels, legends, etc. without translate don't display default language string (English, I suppose):

With language set in "en":
![screenshot-200 40 1 75-2016-10-07-16-34-34](https://cloud.githubusercontent.com/assets/8184347/19203330/0e452ad8-8cad-11e6-90cc-850e6106502e.png)

With language set in "es-419":
![screenshot-200 40 1 75-2016-10-07-16-33-55](https://cloud.githubusercontent.com/assets/8184347/19203352/2de06af6-8cad-11e6-8e42-31ffbd87c4e1.png)

**Comment by daronco** [comment]
That's because Transifex returns empty strings for values that are not translated yet. Rails will use the empty string instead of falling back to the default language (en).

I believe there's a way to download the locales from Transifex without the untranslated strings, need to investigate and then update the locales.
