### ISSUE TITLE
Application configurations: mysql2 raises NameError

### ISSUE THREAD

**Issue by kafussl** [mconf/mconf-web#913]
Hi,
I'm configuring mconf as described in https://github.com/mconf/mconf-web/wiki/Deployment#application-configurations on a brand new xubuntu 16.04 (Linux mconf-server 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
After solving some issues with imagemagick I tried to execute
`RAILS_ENV=production bundle exec rake db:drop db:create db:reset`
which results in 
```(in /var/www/mconf-web/current)
rake aborted!
NameError: uninitialized constant Mysql2::Client::SECURE_CONNECTION
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:12:in `<class:Client>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:2:in `<module:Mysql2>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:1:in `<top (required)>'
/var/www/mconf-web/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.16/lib/mysql2.rb:10:in `<top (required)>'
/var/www/mconf-web/current/config/application.rb:13:in `<top (required)>'
/var/www/mconf-web/current/Rakefile:6:in `require'
/var/www/mconf-web/current/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```
A lot of googling did not help since I do not speak ruby. Mysql2 gem is the version 0.4.5, I wanted to use [this](http://stackoverflow.com/questions/35187403/rails-why-is-rake-secret-giving-me-an-error/35278598) but I do not know how to check or change the version of the gem.

**Comment by daronco** [comment]
This probably comes from the fact that you are using Ubuntu 16.04 instead of 14.04 (which is the one Mconf-Web is tested on). We plan on migrating to 16.04 in the future, but haven't done it yet. If you can start again in an Ubuntu 14.04 your life should be easier.

If you need to use 16.04, try updating the version of the gem mysql2, as suggested in the link you pointed to.
Mconf-Web 2.3 uses the [version 0.3.16 of the gem mysql2](https://github.com/mconf/mconf-web/blob/v2.3.0/Gemfile.lock#L291). Try to change this line to 0.3.18 and then run "bundle install" again following [this section](https://github.com/mconf/mconf-web/wiki/Deployment#download-the-application) of the wiki.

**Comment by daronco** [comment]
@kafussl Is this solved?

**Comment by kafussl** [comment]
@daronco sorry for the long wait, after going to xubuntu 14.04 everything works fine so the problem probably still exists but not for me anymore.

**Comment by daronco** [comment]
Thanks @kafussl. The issue is probably with Ubuntu 16.04 only, so we'll fix it when we update the installation steps to Ubuntu 16.04.
